#! /bin/bash

if [[ ! $1 -gt 0 ]]; then
    echo \"$1\" is not a valid problem number.
    exit 1
fi

echo Testing Project Euler Problem \#$1

problemNumber=$1
while [[ ${#problemNumber} < 3 ]]; do
    problemNumber=0$problemNumber
done
hsFile=euler$problemNumber.hs

echo
echo Compiling...
echo
ghc -v0 --make -o heuler.out -O2 -W $hsFile || exit 1
rm *.hi
rm *.o

echo
echo Running...
echo
result=$(time ./heuler.out | tee /dev/tty | tail -n1)
rm heuler.out
echo

intRegex='^-?[0-9]+$'
[[ $result =~ $intRegex ]] && ./eulerCheck.sh $1 "$result" || exit 1

suggestions=$(hlint -n $hsFile)
if [[ -n $suggestions ]]; then
    echo
    echo
    echo "HLint Suggestions:"
    echo
    echo "$suggestions"
fi
