#! /bin/bash

if [[ ! $1 -gt 0 ]]; then
    echo \"$1\" is not a valid problem number.
    exit 1
fi

echo Testing Project Euler Problem \#$1

problemNumber=$1
while [[ ${#problemNumber} < 3 ]]; do
    problemNumber=0$problemNumber
done
pyFile=euler$problemNumber.py

echo
echo Running...
echo
result=$(time pypy $pyFile | tee /dev/tty | tail -n1)
echo

intRegex='^-?[0-9]+$'
[[ $result =~ $intRegex ]] && ./eulerCheck.sh $1 "$result" || exit 1

